### ISSUE TITLE
num/@type teilweise fehlerhaft belegt

### ISSUE THREAD

**Issue by schassan** [i-d-e/ride#23]
Be manchen Fragen wird `<num type="booleanX">` belegt, was eigentlich type=boolean" sein sollte.

Beispiel: https://github.com/i-d-e/ride/blob/master/issues/issue07/faust/faust-tei.xml

**Comment by hennyu** [comment]
Das ist absichtlich booleanX, weil es nicht nur yes-no, sondern yes-no-not applicable oder yes-no-unknown sein kann
